hello world
wget upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_United_Arab_Emirates.svg/90px-Flag_of_the_United_Arab_Emirates.svg.png -O AED.png
wget upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Afghanistan.svg/90px-Flag_of_Afghanistan.svg.png -O AFN.png
wget upload.wikimedia.org/wikipedia/commons/thumb/3/36/Flag_of_Albania.svg/90px-Flag_of_Albania.svg.png -O ALL.png
wget upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Flag_of_Armenia.svg/90px-Flag_of_Armenia.svg.png -O AMD.png
wget upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Flag_of_Cura%C3%A7ao.svg/90px-Flag_of_Cura%C3%A7ao.svg.png -O ANG.png
wget upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Flag_of_Angola.svg/90px-Flag_of_Angola.svg.png -O AOA.png
wget upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/90px-Flag_of_Argentina.svg.png -O ARS.png
wget upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Flag_of_Australia.svg/90px-Flag_of_Australia.svg.png -O AUD.png
wget upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Flag_of_Aruba.svg/90px-Flag_of_Aruba.svg.png -O AWG.png
wget upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/90px-Flag_of_Azerbaijan.svg.png -O AZN.png
wget upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Flag_of_Bosnia_and_Herzegovina.svg/90px-Flag_of_Bosnia_and_Herzegovina.svg.png -O BAM.png
wget upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Flag_of_Barbados.svg/90px-Flag_of_Barbados.svg.png -O BBD.png
wget upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/90px-Flag_of_Bangladesh.svg.png -O BDT.png
wget upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Bulgaria.svg/90px-Flag_of_Bulgaria.svg.png -O BGN.png
wget upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Bahrain.svg/90px-Flag_of_Bahrain.svg.png -O BHD.png
wget upload.wikimedia.org/wikipedia/commons/thumb/5/50/Flag_of_Burundi.svg/90px-Flag_of_Burundi.svg.png -O BIF.png
wget upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Flag_of_Bermuda.svg/90px-Flag_of_Bermuda.svg.png -O BMD.png
wget upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Brunei.svg/90px-Flag_of_Brunei.svg.png -O BND.png
wget upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Bolivia.svg/90px-Flag_of_Bolivia.svg.png -O BOB.png
wget upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Bolivia.svg/90px-Flag_of_Bolivia.svg.png -O BOV.png
wget upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Brazil.svg/90px-Flag_of_Brazil.svg.png -O BRL.png
wget upload.wikimedia.org/wikipedia/commons/thumb/9/93/Flag_of_the_Bahamas.svg/90px-Flag_of_the_Bahamas.svg.png -O BSD.png
wget upload.wikimedia.org/wikipedia/commons/thumb/9/91/Flag_of_Bhutan.svg/90px-Flag_of_Bhutan.svg.png -O BTN.png
wget upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_Botswana.svg/90px-Flag_of_Botswana.svg.png -O BWP.png
wget upload.wikimedia.org/wikipedia/commons/thumb/8/85/Flag_of_Belarus.svg/90px-Flag_of_Belarus.svg.png -O BYR.png
wget upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Flag_of_Belize.svg/90px-Flag_of_Belize.svg.png -O BZD.png
wget upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Flag_of_Canada.svg/90px-Flag_of_Canada.svg.png -O CAD.png
wget upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Democratic_Republic_of_the_Congo.svg/90px-Flag_of_the_Democratic_Republic_of_the_Congo.svg.png -O CDF.png
wget upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Switzerland.svg/16px-Flag_of_Switzerland.svg.png -O CHE.png
wget upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Switzerland.svg/16px-Flag_of_Switzerland.svg.png -O CHF.png
wget upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Switzerland.svg/16px-Flag_of_Switzerland.svg.png -O CHW.png
wget upload.wikimedia.org/wikipedia/commons/thumb/7/78/Flag_of_Chile.svg/90px-Flag_of_Chile.svg.png -O CLF.png
wget upload.wikimedia.org/wikipedia/commons/thumb/7/78/Flag_of_Chile.svg/90px-Flag_of_Chile.svg.png -O CLP.png
wget upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/90px-Flag_of_the_People%27s_Republic_of_China.svg.png -O CNY.png
wget upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/90px-Flag_of_Colombia.svg.png -O COP.png
wget upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/90px-Flag_of_Colombia.svg.png -O COU.png
wget upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Flag_of_Costa_Rica.svg/90px-Flag_of_Costa_Rica.svg.png -O CRC.png
wget upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Flag_of_Cuba.svg/90px-Flag_of_Cuba.svg.png -O CUC.png
wget upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Flag_of_Cuba.svg/90px-Flag_of_Cuba.svg.png -O CUP.png
wget upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Cape_Verde.svg/90px-Flag_of_Cape_Verde.svg.png -O CVE.png
wget upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_Czech_Republic.svg/90px-Flag_of_the_Czech_Republic.svg.png -O CZK.png
wget upload.wikimedia.org/wikipedia/commons/thumb/3/34/Flag_of_Djibouti.svg/90px-Flag_of_Djibouti.svg.png -O DJF.png
wget upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/90px-Flag_of_Denmark.svg.png -O DKK.png
wget upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_the_Dominican_Republic.svg/90px-Flag_of_the_Dominican_Republic.svg.png -O DOP.png
wget upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Algeria.svg/90px-Flag_of_Algeria.svg.png -O DZD.png
wget upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Egypt.svg/90px-Flag_of_Egypt.svg.png -O EGP.png
wget upload.wikimedia.org/wikipedia/commons/thumb/2/29/Flag_of_Eritrea.svg/90px-Flag_of_Eritrea.svg.png -O ERN.png
wget upload.wikimedia.org/wikipedia/commons/thumb/7/71/Flag_of_Ethiopia.svg/90px-Flag_of_Ethiopia.svg.png -O ETB.png
wget upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Flag_of_the_United_Kingdom.svg/90px-Flag_of_the_United_Kingdom.svg.png -O EUR.png
wget upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Fiji.svg/90px-Flag_of_Fiji.svg.png -O FJD.png
wget upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_the_Falkland_Islands.svg/90px-Flag_of_the_Falkland_Islands.svg.png -O FKP.png
wget upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Flag_of_the_United_Kingdom.svg/90px-Flag_of_the_United_Kingdom.svg.png -O GBP.png
wget upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Georgia.svg/90px-Flag_of_Georgia.svg.png -O GEL.png
wget upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Ghana.svg/90px-Flag_of_Ghana.svg.png -O GHS.png
wget upload.wikimedia.org/wikipedia/commons/thumb/0/02/Flag_of_Gibraltar.svg/90px-Flag_of_Gibraltar.svg.png -O GIP.png
wget upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_The_Gambia.svg/90px-Flag_of_The_Gambia.svg.png -O GMD.png
wget upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Flag_of_Guinea.svg/90px-Flag_of_Guinea.svg.png -O GNF.png
wget upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Flag_of_Guatemala.svg/90px-Flag_of_Guatemala.svg.png -O GTQ.png
wget upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_Guyana.svg/90px-Flag_of_Guyana.svg.png -O GYD.png
wget upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Flag_of_Hong_Kong.svg/90px-Flag_of_Hong_Kong.svg.png -O HKD.png
wget upload.wikimedia.org/wikipedia/commons/thumb/8/82/Flag_of_Honduras.svg/90px-Flag_of_Honduras.svg.png -O HNL.png
wget upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/90px-Flag_of_Croatia.svg.png -O HRK.png
wget upload.wikimedia.org/wikipedia/commons/thumb/5/56/Flag_of_Haiti.svg/90px-Flag_of_Haiti.svg.png -O HTG.png
wget upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Flag_of_Hungary.svg/90px-Flag_of_Hungary.svg.png -O HUF.png
wget upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/90px-Flag_of_Indonesia.svg.png -O IDR.png
wget upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Israel.svg/90px-Flag_of_Israel.svg.png -O ILS.png
wget upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_India.svg/90px-Flag_of_India.svg.png -O INR.png
wget upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Flag_of_Iraq.svg/90px-Flag_of_Iraq.svg.png -O IQD.png
wget upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/90px-Flag_of_Iran.svg.png -O IRR.png
wget upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Iceland.svg/90px-Flag_of_Iceland.svg.png -O ISK.png
wget upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Jamaica.svg/90px-Flag_of_Jamaica.svg.png -O JMD.png
wget upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Flag_of_Jordan.svg/90px-Flag_of_Jordan.svg.png -O JOD.png
wget upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/90px-Flag_of_Japan.svg.png -O JPY.png
wget upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Kenya.svg/90px-Flag_of_Kenya.svg.png -O KES.png
wget upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Flag_of_Kyrgyzstan.svg/90px-Flag_of_Kyrgyzstan.svg.png -O KGS.png
wget upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_Cambodia.svg/90px-Flag_of_Cambodia.svg.png -O KHR.png
wget upload.wikimedia.org/wikipedia/commons/thumb/9/94/Flag_of_the_Comoros.svg/90px-Flag_of_the_Comoros.svg.png -O KMF.png
wget upload.wikimedia.org/wikipedia/commons/thumb/5/51/Flag_of_North_Korea.svg/90px-Flag_of_North_Korea.svg.png -O KPW.png
wget upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/90px-Flag_of_South_Korea.svg.png -O KRW.png
wget upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Flag_of_Kuwait.svg/90px-Flag_of_Kuwait.svg.png -O KWD.png
wget upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_the_Cayman_Islands.svg/90px-Flag_of_the_Cayman_Islands.svg.png -O KYD.png
wget upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Kazakhstan.svg/90px-Flag_of_Kazakhstan.svg.png -O KZT.png
wget upload.wikimedia.org/wikipedia/commons/thumb/5/56/Flag_of_Laos.svg/90px-Flag_of_Laos.svg.png -O LAK.png
wget upload.wikimedia.org/wikipedia/commons/thumb/5/59/Flag_of_Lebanon.svg/90px-Flag_of_Lebanon.svg.png -O LBP.png
wget upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Sri_Lanka.svg/90px-Flag_of_Sri_Lanka.svg.png -O LKR.png
wget upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Flag_of_Liberia.svg/90px-Flag_of_Liberia.svg.png -O LRD.png
wget upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Flag_of_Lesotho.svg/90px-Flag_of_Lesotho.svg.png -O LSL.png
wget upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Libya.svg/90px-Flag_of_Libya.svg.png -O LYD.png
wget upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Morocco.svg/90px-Flag_of_Morocco.svg.png -O MAD.png
wget upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Moldova.svg/90px-Flag_of_Moldova.svg.png -O MDL.png
wget upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Madagascar.svg/90px-Flag_of_Madagascar.svg.png -O MGA.png
wget upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Flag_of_Macedonia.svg/90px-Flag_of_Macedonia.svg.png -O MKD.png
wget upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Flag_of_Myanmar.svg/90px-Flag_of_Myanmar.svg.png -O MMK.png
wget upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Mongolia.svg/90px-Flag_of_Mongolia.svg.png -O MNT.png
wget upload.wikimedia.org/wikipedia/commons/thumb/6/63/Flag_of_Macau.svg/90px-Flag_of_Macau.svg.png -O MOP.png
wget upload.wikimedia.org/wikipedia/commons/thumb/4/43/Flag_of_Mauritania.svg/90px-Flag_of_Mauritania.svg.png -O MRO.png
wget upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Mauritius.svg/90px-Flag_of_Mauritius.svg.png -O MUR.png
wget upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Maldives.svg/90px-Flag_of_Maldives.svg.png -O MVR.png
wget upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Flag_of_Malawi.svg/90px-Flag_of_Malawi.svg.png -O MWK.png
wget upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/90px-Flag_of_Mexico.svg.png -O MXN.png
wget upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/90px-Flag_of_Mexico.svg.png -O MXV.png
wget upload.wikimedia.org/wikipedia/commons/thumb/6/66/Flag_of_Malaysia.svg/90px-Flag_of_Malaysia.svg.png -O MYR.png
wget upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Mozambique.svg/90px-Flag_of_Mozambique.svg.png -O MZN.png
wget upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Namibia.svg/90px-Flag_of_Namibia.svg.png -O NAD.png
wget upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_Nigeria.svg/90px-Flag_of_Nigeria.svg.png -O NGN.png
wget upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Nicaragua.svg/90px-Flag_of_Nicaragua.svg.png -O NIO.png
wget upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/90px-Flag_of_Norway.svg.png -O NOK.png
wget upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Flag_of_Nepal.svg/16px-Flag_of_Nepal.svg.png -O NPR.png
wget upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Flag_of_New_Zealand.svg/90px-Flag_of_New_Zealand.svg.png -O NZD.png
wget upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Oman.svg/90px-Flag_of_Oman.svg.png -O OMR.png
wget upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Flag_of_Panama.svg/90px-Flag_of_Panama.svg.png -O PAB.png
wget upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Flag_of_Peru.svg/90px-Flag_of_Peru.svg.png -O PEN.png
wget upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Flag_of_Papua_New_Guinea.svg/90px-Flag_of_Papua_New_Guinea.svg.png -O PGK.png
wget upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_the_Philippines.svg/90px-Flag_of_the_Philippines.svg.png -O PHP.png
wget upload.wikimedia.org/wikipedia/commons/thumb/3/32/Flag_of_Pakistan.svg/90px-Flag_of_Pakistan.svg.png -O PKR.png
wget upload.wikimedia.org/wikipedia/commons/thumb/1/12/Flag_of_Poland.svg/90px-Flag_of_Poland.svg.png -O PLN.png
wget upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Paraguay.svg/90px-Flag_of_Paraguay.svg.png -O PYG.png
wget upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Qatar.svg/90px-Flag_of_Qatar.svg.png -O QAR.png
wget upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Romania.svg/90px-Flag_of_Romania.svg.png -O RON.png
wget upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Flag_of_Serbia.svg/90px-Flag_of_Serbia.svg.png -O RSD.png
wget upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Russia.svg/90px-Flag_of_Russia.svg.png -O RUB.png
wget upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Rwanda.svg/90px-Flag_of_Rwanda.svg.png -O RWF.png
wget upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/90px-Flag_of_Saudi_Arabia.svg.png -O SAR.png
wget upload.wikimedia.org/wikipedia/commons/thumb/7/74/Flag_of_the_Solomon_Islands.svg/90px-Flag_of_the_Solomon_Islands.svg.png -O SBD.png
wget upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Seychelles.svg/90px-Flag_of_Seychelles.svg.png -O SCR.png
wget upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Sudan.svg/90px-Flag_of_Sudan.svg.png -O SDG.png
wget upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Sweden.svg/90px-Flag_of_Sweden.svg.png -O SEK.png
wget upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/90px-Flag_of_Singapore.svg.png -O SGD.png
wget upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Saint_Helena.svg/90px-Flag_of_Saint_Helena.svg.png -O SHP.png
wget upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Sierra_Leone.svg/90px-Flag_of_Sierra_Leone.svg.png -O SLL.png
wget upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Flag_of_Somalia.svg/90px-Flag_of_Somalia.svg.png -O SOS.png
wget upload.wikimedia.org/wikipedia/commons/thumb/6/60/Flag_of_Suriname.svg/90px-Flag_of_Suriname.svg.png -O SRD.png
wget upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Flag_of_South_Sudan.svg/90px-Flag_of_South_Sudan.svg.png -O SSP.png
wget upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Sao_Tome_and_Principe.svg/90px-Flag_of_Sao_Tome_and_Principe.svg.png -O STD.png
wget upload.wikimedia.org/wikipedia/commons/thumb/5/53/Flag_of_Syria.svg/90px-Flag_of_Syria.svg.png -O SYP.png
wget upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Flag_of_Swaziland.svg/90px-Flag_of_Swaziland.svg.png -O SZL.png
wget upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_Thailand.svg/90px-Flag_of_Thailand.svg.png -O THB.png
wget upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Tajikistan.svg/90px-Flag_of_Tajikistan.svg.png -O TJS.png
wget upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Turkmenistan.svg/90px-Flag_of_Turkmenistan.svg.png -O TMT.png
wget upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Tunisia.svg/90px-Flag_of_Tunisia.svg.png -O TND.png
wget upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Tonga.svg/90px-Flag_of_Tonga.svg.png -O TOP.png
wget upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/90px-Flag_of_Turkey.svg.png -O TRY.png
wget upload.wikimedia.org/wikipedia/commons/thumb/6/64/Flag_of_Trinidad_and_Tobago.svg/90px-Flag_of_Trinidad_and_Tobago.svg.png -O TTD.png
wget upload.wikimedia.org/wikipedia/commons/thumb/7/72/Flag_of_the_Republic_of_China.svg/90px-Flag_of_the_Republic_of_China.svg.png -O TWD.png
wget upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Tanzania.svg/90px-Flag_of_Tanzania.svg.png -O TZS.png
wget upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Ukraine.svg/90px-Flag_of_Ukraine.svg.png -O UAH.png
wget upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Flag_of_Uganda.svg/90px-Flag_of_Uganda.svg.png -O UGX.png
wget upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/90px-Flag_of_the_United_States.svg.png -O USD.png
wget upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/90px-Flag_of_the_United_States.svg.png -O USN.png
wget upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/90px-Flag_of_the_United_States.svg.png -O USS.png
wget upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Uruguay.svg/90px-Flag_of_Uruguay.svg.png -O UYI.png
wget upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Uruguay.svg/90px-Flag_of_Uruguay.svg.png -O UYU.png
wget upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Uzbekistan.svg/90px-Flag_of_Uzbekistan.svg.png -O UZS.png
wget upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flag_of_Venezuela.svg/90px-Flag_of_Venezuela.svg.png -O VEF.png
wget upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Vietnam.svg/90px-Flag_of_Vietnam.svg.png -O VND.png
wget upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Vanuatu.svg/90px-Flag_of_Vanuatu.svg.png -O VUV.png
wget upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Samoa.svg/90px-Flag_of_Samoa.svg.png -O WST.png
wget upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Cameroon.svg/90px-Flag_of_Cameroon.svg.png -O XAF.png
wget upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Anguilla.svg/90px-Flag_of_Anguilla.svg.png -O XCD.png
wget upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Benin.svg/90px-Flag_of_Benin.svg.png -O XOF.png
wget upload.wikimedia.org/wikipedia/commons/thumb/d/db/Flag_of_French_Polynesia.svg/90px-Flag_of_French_Polynesia.svg.png -O XPF.png
wget upload.wikimedia.org/wikipedia/commons/thumb/8/89/Flag_of_Yemen.svg/90px-Flag_of_Yemen.svg.png -O YER.png
wget upload.wikimedia.org/wikipedia/commons/thumb/a/af/Flag_of_South_Africa.svg/90px-Flag_of_South_Africa.svg.png -O ZAR.png
wget upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flag_of_Zambia.svg/90px-Flag_of_Zambia.svg.png -O ZMW.png
